version: '3.8'
services:

  #jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
  #collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.51.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133" # Health check extension
    depends_on:
      - jaeger-all-in-one